export const GET_ALLCHECK_INFORMATION = 'GET_ALLCHECK_INFORMATION'
export const GET_TODAYCHECK_INFORMATION = 'GET_TODAYCHECK_INFORMATION'
export const GET_YEARCHECK_INFORMATION = 'GET_YEARCHECK_INFORMATION'
export const GET_ALLLEAVE_INFORMATION = 'GET_ALLLEAVE_INFORMATION'
export const GET_ALLREST_INFORMATION = 'GET_ALLREST_INFORMATION'

