export const GET_LEAVE_INFORMATION = "GET_LEAVE_INFORMATION";
export const GET_LEAVEBYID_INFORMATION = "GET_LEAVEBYID_INFORMATION";
export const GET_LEAVEREQ_INFORMATION = "GET_LEAVEREQ_INFORMATION";
