export const GET_MEETINGROOM_INFORMATION = 'GET_MEETINGROOM_INFORMATION'
export const GET_MEETINGBYID_INFORMATION = 'GET_MEETINGBYID_INFORMATION'
export const GET_MEETINGBYMULTIID_INFORMATION = 'GET_MEETINGBYMULTIID_INFORMATION'
export const GET_MEETINGBYROOMID_INFORMATION = 'GET_MEETINGBYROOMID_INFORMATION'

