export const GET_HOLIDAYS_INFORMATION = 'GET_HOLIDAYS_INFORMATION'
export const GET_WORKINGTIME_INFORMATION = 'GET_WORKINGTIME_INFORMATION'
export const GET_DAYOFF_INFORMATION = 'GET_DAYOFF_INFORMATION'